### ISSUE TITLE
Re.execp apparently allocating for no reason

### ISSUE THREAD

**Issue by sliquister** [ocaml/ocaml-re#105]
Hello,

Re.execp is implemented by calling exec_internal, which passes true to the argument group of match_str. In fact, that argument is always true. Why not pass false to avoid allocating a 10 element array all the time?

**Comment by rgrinberg** [comment]
You bring up a good point. Seems like the same point applies to `exec_partial` as well. Should be easy  enough to address with an extra param for `exec_internal`.

**Comment by sliquister** [comment]
Now that you mention `exec_partial`, I see that the parameter `partial` of `match_str` is always `false`. I don't really know what it does, but judging from the name, maybe `exec_partial` could be further optimized by passing `true`.

**Comment by sliquister** [comment]
Thank you!
