### ISSUE TITLE
Question about exec_partial

### ISSUE THREAD

**Issue by trefis** [ocaml/ocaml-re#13]
Hi!

The last few days I've tried to use `Re.exec_partial` both before the last patch (related to #11 ) and after it.
And I don't think I quite understand how it is supposed to work. Naïvely I thought that you would get the "`Partial" answer when your string is recognized as a prefix of an "accepted" pattern, but it seems that is not the case.

Here is what I had before the last patch :

``` ocaml
# let r = Re.compile (Re.str "let");;
val r : Re.re = <abstr>
# Re.exec_partial r "l";;
- : [ `Full | `Mismatch | `Partial ] = `Mismatch
# Re.exec_partial r "let";;
- : [ `Full | `Mismatch | `Partial ] = `Full
# Re.exec_partial r "ileti";;
- : [ `Full | `Mismatch | `Partial ] = `Full 
```

And here is what I get now :

``` ocaml
# let r = Re.compile (Re.str "let");;
val r : Re.re = <abstr>
# Re.exec_partial r "l";;
- : [ `Full | `Mismatch | `Partial ] = `Partial
 # Re.exec_partial r "let";;
- : [ `Full | `Mismatch | `Partial ] = `Partial
# Re.exec_partial r "ileti";;
- : [ `Full | `Mismatch | `Partial ] = `Full
# Re.exec_partial r "abc";;
- : [ `Full | `Mismatch | `Partial ] = `Partial    
```

So I don't know if it is buggy (I'm particularly worried by the last result) or if I completly misunderstood how it is supposed to work.

I would appreciate some pointers.

**Comment by dwang20151005** [comment]
I think this bug may have reappeared.  See PR #164 for some tests.  Some of them directly contradict examples given this thread but others might be my misunderstanding.
