### ISSUE TITLE
Installation instructions incomplete

### ISSUE THREAD

**Issue by mehdid** [ocaml/ocaml-re#157]
README.md mentions `make install` to install the library but this target no longer exists.

What is the procedure to install the library? (without opam)

**Comment by rgrinberg** [comment]
Give `$ jbuilder install` a try.

**Comment by mehdid** [comment]
Sorry for not having been accurate, I meant INSTALL instead of README.md.

I've used `jbuilder install` indeed (after a few customizations). But INSTALL file is still out-dated. It might be worth updating it, or deleting it all together.

**Comment by rgrinberg** [comment]
Okay, I see. I'll update the README
