### ISSUE TITLE
Match whole string with glob pattern

### ISSUE THREAD

**Issue by farao** [ocaml/ocaml-re#168]
I'm not sure if this works already, but I haven't found a way:
I want to match a glob pattern, e.g. "test*" with a whole string, so I would like the string "test123" to match but "123test123" not. How can I achieve this?

`Re.execp (Re.Glob.glob "test*" |> Re.compile) "123test123";;` unfortunately returns true...

In "normal" regular expressions there's the workaround that if you don't have such a function that matches the whole string, you can change your pattern to "^test.*$" but ^ and $ do not exist for globs.

**Comment by bcc32** [comment]
`Re.Glob.glob` returns an `Re.t` which you can then combine with the `bos` and `eos` patterns:

```ocaml
utop # Re.execp (Re.seq [ Re.bos; Re.Glob.glob "test*"; Re.eos ] |> Re.compile) "123test123";;
- : bool = false                                                                                                                                                          
```

**Comment by farao** [comment]
Thanks! Sorry, forgot to close this...
