### ISSUE TITLE
what encoding does `Re` use?

### ISSUE THREAD

**Issue by dwang20151005** [ocaml/ocaml-re#173]
It's at least ASCII-compatible.  We thought it might be Latin1, but `Core.punct` accepts `0xA0`.

In Latin1 `0xA0` encodes a non-breaking space: https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Code_page_layout

**Comment by Drup** [comment]
Officially, `Re` is only aware of US-ASCII. For other encoding, you are encouraged to use your own character classes.

**Comment by bcc32** [comment]
It seems like `Core.alpha` and such accept non-ASCII bytes (specifically, Latin-1 alphabetic characters like accented letters) as alphabetic characters.  I don't think that matches the description "only aware of US-ASCII"---should `alpha` and similar constructors change to more strictly adhere to US-ASCII?

**Comment by Drup** [comment]
It does, because it has been present for a long time and removing them would break many programs silently. However, I would advise you define your own character classes if it's really important to you.

**Comment by dwang20151005** [comment]
I think you are saying that the character classes that ship with Re
match some undocument superset of ascii, but not exactly Latin1, and
if we want character classes that match exactly some standard encoding
we should define them ourselves.

If I understand your reply correctly, would you accept any of these
pull requests?

1. Change the character classes in Re to match exactly Latin1, since
they're already pretty close.
2. Add sub-modules of Core whose character classes match exactly some
standard encoding, e.g., Core.Ascii or Core.Latin1.
3. Add a doc comment warning users of the current behavior.

**Comment by Drup** [comment]
> 2. Add sub-modules of Core whose character classes match exactly some standard encoding, e.g., Core.Ascii or Core.Latin1.

I would vote for this one. 

After that ... maybe deprecate the standard one ? I'm not sure, they are used by pretty much everyone. Maybe we could use alerts ... @rgrinberg  ?

**Comment by rgrinberg** [comment]
What minimum version of ocaml do alerts impose?

**Comment by dwang20151005** [comment]
https://caml.inria.fr/pub/docs/manual-ocaml/alerts.html says 4.08

**Comment by Drup** [comment]
That's fine, It uses attributes. It'll trigger only on recent ocaml versions, but doesn't break compat.

**Comment by dwang20151005** [comment]
> Add sub-modules of Core whose character classes match exactly some
standard encoding, e.g., Core.Ascii or Core.Latin1.

Sounds like everyone's on board with this one?

>
