### ISSUE TITLE
These PCRE regular expressions from the Agda syntax highlighter fail to parse

### ISSUE THREAD

**Issue by TrulyNonstrict** [ocaml/ocaml-re#174]
Hello! I want to use this library to write a syntax highlighter. I would like my program to be usable with the data that GitHub uses for its syntax highlighting. I'm currently testing my program on the Agda grammar: https://github.com/agda/agda-github-syntax-highlighting

According to https://github.com/github/linguist/blob/master/CONTRIBUTING.md, GitHub's Linguist library uses the PCRE dialect. However, the Pcre module of this library fails on the following inputs:

```ocaml
let tests =
  [ {regex|(?<=^|[[:space:]\(\){}])(-?\d+|0x[0-9A-F]+|-?\d+\.\d+((e|E)(\+|-)?\d+)?|-?\d+(e|E)(\+|-)?\d+)(?=[[:space:]\(\){}])|regex}
  ; {regex|((?<=^|[.;\(\){}@"[:space:]])\?(?=[.;\(\){}@"[:space:]])|{!.*!})|regex}
  ; {regex|\b(Set|Prop)[0123456789₀₁₂₃₄₅₆₇₈₉]*(?=$|[[:space:]\(\)\{\}])|regex}
  ; {regex|(?<=^|[[:space:]\(\)\{\}])(λ|→|->|∀|=|←|:)(?=[[:space:]\(\)\{\}])|regex}
  ; {regex|^[[:space:]]*(((abstract|instance|macro|pattern|postulate|primitive|private|syntax|variable|where|let)[[:space:]]+)*)((([^;\(\){}@"[:space:]]+)[[:space:]]+)+)(?=:)|regex}
  ; {regex|(?<=^|[[:space:]\(\){}])(abstract|constructor|data|do|eta-equality|field|forall|hiding|import|in|inductive|infix|infixl|infixr|instance|let|macro|module|mutual|no-eta-equality|open|overlap|pattern|postulate|primitive|private|public|quote|quoteContext|quoteGoal|quoteTerm|record|renaming|rewrite|syntax|tactic|unquote|unquoteDecl|unquoteDef|using|variable|where|with)(?=$|[[:space:]\(\){}])|regex}
  ]

let () =
  List.iter (fun s ->
      try ignore (Re.Pcre.re s) with
      | Re.Perl.Parse_error ->
         print_endline s;
         print_newline ()
    ) tests
```

all of which are from the Agda repo. I am not a Regex expert, so I do not know which features are causing the issue. I am using version 1.9.0 of this library.

Thank you for your time!

**Comment by bcc32** [comment]
This library doesn't support look-aheads and look-behinds (`(?<=` and `(?=`), since it is a DFA-based regex implementation, rather than a backtracking-based implementation.  You'd have to use different patterns with this library.  I'm not familiar with Agda, so I don't know if its grammar would be amenable to being expressed with a regular grammar.

**Comment by TrulyNonstrict** [comment]
Thank you! Because I'm not good enough at regex to rewrite the patterns and I want to be liberal in the features that I support, I've decided to use the [pcre](https://opam.ocaml.org/packages/pcre/) package, which provide bindings to PCRE and supports backtracking. In the future, if I decide to rethink my design, I may come back to this library.
