### ISSUE TITLE
Re.Emacs - matching exact number of occurences using {m,n}

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [ocaml/ocaml-re#175]
Thanks for this library! I'm new to the OCaml world and just tried this library and found an issue(?).

When I compile this regex to specify the exact number of occurrence using Re.Emacs, it doesn't seem to match 5 digit strings like "01234"
```
[0-9]{5}
```
The same string matches when I compile it using `Re.Perl` module.

**Comment by bcc32** [comment]
In Emacs regular expressions, `{` matches a literal curly brace character by default.  If you want the special behavior, you have to use `\{` and `\}` instead.  See [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Backslash.html) for instance.
