### ISSUE TITLE
Glob: Double asterisk is not matching zero directories

### ISSUE THREAD

**Issue by eWert-Online** [ocaml/ocaml-re#185]
Using the latest (unreleased) version with #172 already merged, I would expect `**` to match _zero_ or more directories.

Given the following two paths

`/project/path/test/lib/test.ml`
`/project/path/test/lib/deep/test2.ml`

with the pattern `test/lib/**/*.ml`, I would expect both to be true. 
Right now however, only the second (deep) one matches.

Doing the same without the `lib` like this `test/**/*.ml` returns both paths as true.

This leads me to the conclusion, that `**` right now means _one_ or more directories.

(Related to #171)

**Comment by rgrinberg** [comment]
@sliquister do you agree that this is a bug?

**Comment by sliquister** [comment]
@rgrinberg did you actually mean to ask me?

I don't know how globs are documented right now, but both git and hg would interpret `**` as matching `>= 0` number of directories, so in terms of expectations, it's likely less surprising to interpret `**` similarly, as @eWert-Online is requesting. (I also looked at `fnmatch` but it doesn't have `**` or equivalent, so no comparison possible)

**Comment by rgrinberg** [comment]
I wrongly recalled that it was you who contributed many improvements to the glob api. It was actually another JaneStreet employee. In any case, I assume you are still using `Re.Glob`, in which case we don't want to change the behavior and subtly break things for you.

@eWert-Online since we all seem agree with your assessment, would you like to contribute a fix?

**Comment by eWert-Online** [comment]
My OCaml isn't that good, but I can at least try 🙂

**Comment by eWert-Online** [comment]
I looked into this, but I think solving this is currently a bit too much for me 😄 

I think the problem is, that the parser currently sees the `/`'s as explicitly set characters that need to be present in the path.
In my understanding it should however "swallow" the path segments recursively until it finds its match or runs out of characters. If it encounters a `..` or `.` it should also fail.

I did write some tests, which test all of the above mentioned.
```ml
  assert (re_match    (glob ~anchored "foo/**/bar/**/baz") "foo/bar/baz");
  assert (re_match    (glob ~anchored "foo/**/bar/**/baz") "foo/bar/x/y/z/baz");
  assert (re_match    (glob ~anchored "foo/**/bar/**/baz") "foo/x/y/z/bar/baz");
  assert (re_match    (glob ~anchored "foo/**/bar/**/baz") "foo/bar/x/bar/x/baz");
  assert (re_mismatch (glob ~anchored "foo/**/bar/**/baz") "foo/bar/../x/baz");
  assert (re_mismatch (glob ~anchored "foo/**/bar/**/baz") "foo/bar/./x/baz");
```
