### ISSUE TITLE
Error of global_replace

### ISSUE THREAD

**Issue by chengtie** [ocaml/ocaml-re#195]
I realized that `Str.global_replace (Str.regexp "[ \f\r\t\n]+") "" "if"` returns `"i"`, and `Str.global_replace (Str.regexp "[ \f\r\t\n]+") "" "igf"` returns `"ig"`.

Am I writing the correct regular expression? or is there anything wrong with `global_replace`?

**Comment by bcc32** [comment]
I think you are missing some backslashes in the regular expression.  You need one set of backslashes for the OCaml string literal, and one set for the regexp engine, so: `Str.regexp "[ \\f\\r\\t\\n]+"`.  You could also use a [delimited string](https://ocaml.org/manual/lex.html#sss:stringliterals) like so, to avoid escaping: `Str.regexp {|[ \f\r\t\n]+|}`.

(To go into a bit more detail, unrecognized escape sequences like `\f` are interpreted as the two constituent characters.  So the character class that `Str.regexp` sees contains the backslash character and the `f` character.  You should have seen a warning like `illegal backslash escape in string.`, possibly depending on your compiler version.)

**Comment by chengtie** [comment]
> I think you are missing some backslashes in the regular expression. You need one set of backslashes for the OCaml string literal, and one set for the regexp engine, so: `Str.regexp "[ \\f\\r\\t\\n]+"`. You could also use a [delimited string](https://ocaml.org/manual/lex.html#sss:stringliterals) like so, to avoid escaping: `Str.regexp {|[ \f\r\t\n]+|}`.
> 
> (To go into a bit more detail, unrecognized escape sequences like `\f` are interpreted as the two constituent characters. So the character class that `Str.regexp` sees contains the backslash character and the `f` character. You should have seen a warning like `illegal backslash escape in string.`, possibly depending on your compiler version.)

I tried `(Str.global_replace (Str.regexp "[ \\f\\r\\t\\n]+") "" "if")` and `(Str.global_replace (Str.regexp {|[ \f\r\t\n]+|}) "" "if")` on my side, they both return `i`.

**Comment by bcc32** [comment]
Ah, you are totally right.  My first post was incorrect because escape sequences don't work in character classes (`[]`).  You'll have to use some other escape sequence instead of `\f`, probably `\012`.

```
utop # (Str.global_replace (Str.regexp "[ \012\r\t\n]+") "" "if");;
- : string = "if"
- ```

**Comment by chengtie** [comment]
> Ah, you are totally right. My first post was incorrect because escape sequences don't work in character classes (`[]`). You'll have to use some other escape sequence instead of `\f`, probably `\012`.
> 
> ```ocaml
> utop # (Str.global_replace (Str.regexp "[ \012\r\t\n]+") "" "if");;
> - : string = "if"
> ```

It works now, thank you.
