### ISSUE TITLE
Some functions in the Re module still using deprecated 'substrings' alias

### ISSUE THREAD

**Issue by AshineFoster** [ocaml/ocaml-re#208]
The functions `exec`, `exec_opt`, `all`, etc. in the Re module still uses the `substrings` alias although it has been marked as deprecated.

**Comment by rgrinberg** [comment]
Could you send a PR to fix this?

**Comment by rgrinberg** [comment]
Fixed in https://github.com/ocaml/ocaml-re/pull/246
