### ISSUE TITLE
Cant compile non-greedy dot-star

### ISSUE THREAD

**Issue by arthurmelton** [ocaml/ocaml-re#230]
I was trying to do a non-greedy dot-star (`.*?`). This is helpful when we want to look over some text like this 
```
abc example abc example 2 abc
```

Running the following regex would give the following:

`abc .* abc` = `abc example abc example2 abc`
`abc .*? abc` = `abc example abc`

Currently the top example can be compiled but the bottom one fails with `Re__Posix.Parse_error`

**Comment by vouillon** [comment]
There is no non-greedy star operator in POSIX regular expressions. And since POSIX regular expressions have a longest match semantics, it would not have the behavior you expect.

You should probably use `Re.Pcre` instead of `Re.Posix`.
