### ISSUE TITLE
Re.replace doesn't work with zero-length matches

### ISSUE THREAD

**Issue by glondu** [ocaml/ocaml-re#231]
With re 1.11.0, the following:

    Re.(replace Pcre.(regexp "^$") ~f:(fun _ -> assert false) "")

returns `""`. Is it expected? According to me, there is one match (even though it is zero-length), so `f` should be called once.

Another variation of the phenomenon:

    Re.(all Pcre.(regexp "^$") "")

returns the empty list.

**Comment by vouillon** [comment]
This is fixed by #233.
