### ISSUE TITLE
Should bos, bol, etc. match characters or positions?

### ISSUE THREAD

**Issue by yallop** [ocaml/ocaml-re#55]
I wanted to write a program that inserted a string at the beginning of every line and I was surprised by the behaviour of `replace_string` together with `bol`.

```
# Re.(replace_string (compile bol)) ~by:"z" "abc";;
- : string = "zbc"
```

Is consuming the first character intentional?  Compare the behaviour of `eol`, which doesn't consume the last character:

```
# Re.(replace_string (compile eol)) ~by:"z" "abc";;
- : string = "abcz"
```

Similarly, other regex engines treat `^` as a position rather than a character, e.g. Python

```
>>> re.sub('^', 'z', 'abc')
'zabc'
```

and sed

```
$ sed 's!^!z!' <<< abc
zabc
```

**Comment by rgrinberg** [comment]
This also works for `bow` and others like it as well.

**Comment by vouillon** [comment]
This is in fact a bug in `Re.replace_string`. In  general, we want to search for a further match right after the current match. But for zero-length match, we need to skip a character, otherwise we get into an infinite loop. The issue is that we forget to copy this character.

**Comment by yallop** [comment]
Thanks for fixing this so quickly!
