### ISSUE TITLE
1.3.x and 1.4.x aren't compatible with OCaml < 4.01 due to tests

### ISSUE THREAD

**Issue by dsheets** [ocaml/ocaml-re#62]
Starting in 1.3.0, the `opam` file declared `build-test` which is incompatible with OCaml < 4.01 due to use of `@@` and `|>` in `File "lib_test/test_re.ml", line 28, characters 34-36` and `File "lib_test/test_pcre.ml", line 12, characters 41-43`, respectively.

Could these versions be marked as 4.01+ only or patched? If they aren't patched, should they be marked as 4.01+ only and should a new version (1.4.1) be released with which it is possible to run the tests on OCaml < 4.01?

I don't have a great love for 4.00.1 but it's annoying to have my tests fail because re's tests are using some simple operators.

**Comment by rgrinberg** [comment]
Sure, we'd take a patch to make the tests work against 4.00.1

**Comment by dsheets** [comment]
I can do that for this repo... what about opam-repository?

**Comment by rgrinberg** [comment]
I suppose we can bump the lower bound for old releases after we make a 4.00.1 compatible release.
