### ISSUE TITLE
Glob */foo matches /foo

### ISSUE THREAD

**Issue by bfops** [ocaml/ocaml-re#74]
The glob code is explicitly constructed to match shell behavior, e.g. `*.foo` does not match ".foo". However, `*/foo` matches "/foo", which is incorrect in a shell context.

**Comment by bfops** [comment]
`foo/*` also matches "foo/", which feels wrong.

**Comment by vouillon** [comment]
The `fnmatch` POSIX function gives the same results.

**Comment by bfops** [comment]
Ah it does for me too. I had just assumed that `fnmatch` matched the behavior provided by a shell.
