### ISSUE TITLE
Get rid of dumb top level dir name in tarball please?

### ISSUE THREAD

**Issue by cicku** [ocaml/ocaml-re#75]
Hi,

In case you use `ocaml-$VER` in git tags, could you stop using the whole tag as $VER again in tarball please?

The tarball downloaded contains use `ocaml-re-ocaml-re-1.4.1` as top level of source, looks pretty dumb here, the common way should be ocaml-re-$VER.

**Comment by rgrinberg** [comment]
Agreed. I think we should just remove the `ocaml-re` from the tags. I'm proposing that:

* old tags will stay they are for backwards compatibility
* we'll create aliases of old tags without the `ocaml-re` prefix.
* new tags will come without `ocaml-re` as the prefix.

@avsm @Drup @vouillon thoughts?

**Comment by Drup** [comment]
Fine with me.

**Comment by rgrinberg** [comment]
I've published new tags without the `ocaml-re` prefix. New releases will not include this prefix.
