### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by JoePython1** [ocaml/ocaml-re#78]
Noob here. Is there any documentation for this library?
Thank you

**Comment by marklrh** [comment]
in OCaml, ``.mli`` can serve as an alright documentation. See [re.mli](https://github.com/ocaml/ocaml-re/blob/master/lib/re.mli)

Examples can be found in [lib_test](https://github.com/ocaml/ocaml-re/blob/master/lib_test)

**Comment by JoePython1** [comment]
Wonder what am i doing wrong here?
utop # Re.matches 0 6 "\\d+" "123333" ;;
Error: The function applied to this argument has type                                                                                                                           ?pos:int -> ?len:int -> bytes list                                                                                                                            This argument cannot be applied without label

**Comment by rgrinberg** [comment]
@JoePython1 Could you describe what you're trying to accomplish and we'll do our best to explain how that should be done?

I agree that the documentation for ocaml-re is lacking. I'd like to create some sort of cookbook style docs. Need a few representative use cases though.

**Comment by JoePython1** [comment]
Coming from the python  world, i was looking alternatives for re.compile, re.match, re.split, re.search and re.findall which is very trivial to use in that language. Also note, the re module in python is perl compatible. IMHO Regexp/String manipulation should be trivial like what is provided in Python/Perl/Ruby worlds. This will allow low barrier to entry for a typed language like Ocaml for noobs like me. 
Thank you for responding.

**Comment by rgrinberg** [comment]
Note that OCaml does have pcre just like perl/python: https://github.com/mmottl/pcre-ocaml

To address your point though, using this library isn't much harder than using than the perl/python equivalent.

Here's one quick example:

```ocaml
#require "re.pcre";;
let re = Re_pcre.regexp "\\d+"
let () =
  "one 123 two 456 three 789"
  |> Re.all re
  |> List.iter (fun match_ -> Printf.printf "Match: %s\n" (Re.get match_ 0))
```

If you have any concrete questions we're happy to address them here. Hopefully improve the documentation in the process as well.

**Comment by JoePython1** [comment]
Thank you for the supportive responses.

**Comment by boechat107** [comment]
https://ocaml.org/p/re/latest/doc/index.html
